name: millie
dependencies:
  args: ^1.0.0
  code_buffer: ^1.0.0
  file: ^2.0.0
  linear_memory: ^1.0.0
  path: ^1.4.0
  process: ^2.0.0
  process_plus: ^1.0.0
  string_scanner: ^1.0.0
  symbol_table: ^1.0.0
  tuple: ^1.0.0
  vector_math: ^2.0.0
dev_dependencies:
  test: ^0.12.0
